### ISSUE TITLE
MaterialSegmentedControl frame stay to CGRect.zero when initialising segments with constructor

### ISSUE THREAD

**Issue by OxyFlax** [twho/material-design-widgets-lite-ios#3]
I have created a view in the storyboard and I'm trying to put the MaterialSegmentedControl in this view but it keeps the frame CGRect.zero and I can not force it to be my view frame.

```
let segmentedControl = MaterialSegmentedControl(segments: segments, selectorStyle: .line, textColor: .darkGray, selectorTextColor: .blue, selectorColor: .white, bgColor: .white)

// segmentedControl.frame = self.topView.frame

self.topView.addSubview(segmentedControl)
```

**Comment by twho** [comment]
I would recommend you use [AutoLayout](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/index.html). 

**Step 1.** Add this line after adding the view to ```topView```
```swift
segmentedControl.translatesAutoresizingMaskIntoConstraints = false
```
**Step 2.** In your view controller, add the following code.
```swift
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    segmentedControl.leftAnchor.constraint(equalTo: topView.leftAnchor).isActive = true
    segmentedControl.rightAnchor.constraint(equalTo: topView.rightAnchor).isActive = true
    segmentedControl.topAnchor.constraint(equalTo: topView.topAnchor).isActive = true
    segmentedControl.bottomAnchor.constraint(equalTo: topView.bottomAnchor).isActive = true
}
```
This way, the frame of the ```segmentedControl``` should be forced to align with your view's frame. Let me know if this does not work.

**Comment by OxyFlax** [comment]
I am using AutoLayout thanks.
I have the same crash in LayoutSubview first line:
`selector.bottomAnchor.constraint(equalTo: self.bottomAnchor).isActive = true`
Expected found nil...

**Comment by twho** [comment]
Well this sounds like you a bug you have to figure out yourself. What does `self` refer to there? There might be a problem if it is not an `UIView`.

**Comment by OxyFlax** [comment]
self refers to the UIViewController. TopView is an IBOutlet linked with the storyboard: 
`@IBOutlet var topView: UIView!`

**Comment by twho** [comment]
Right then you shouldn't use `self` there, `UIViewController` is not `UIView`. Use `self.view` or `topView` instead.

**Comment by OxyFlax** [comment]
`self.topView` or `topView` refers to the same object. i just tried with topView and have the same issue

**Comment by twho** [comment]
It's an issue you have to fix there. I don't think it's related to segmented control itself though.

**Comment by OxyFlax** [comment]
Well the issue is happening in the `layoutSubviews` function of the MaterialSegmentedControl class, that's why I think it is related to this. Do you have a sample of a full implementation of the Segmented control? Cause the sample I found or the nice tutorial on medium are not up to date with the framework

**Comment by twho** [comment]
Try this:
```swift
let segmentedControl = MaterialSegmentedControl(selectorStyle: .line, textColor: .black, selectorTextColor: .black, selectorColor: .black, bgColor: .white)

for i in 0..<3 {
    let button = MaterialButton(text: "Segment \(i)", textColor: .gray, bgColor: .clear, cornerRadius: 12.0)
    button.rippleLayerAlpha = 0.15
    segmentedControl.segments.append(button)
}
```
Then add it to your whatever parent view and deal with its layout constraints. There is a MaterialDesignWidgetsDemo included in this repo, you may refer to that.

**Comment by OxyFlax** [comment]
Ok I identified the issue.
Actually when we add the segments with `append`, it works well, but when we define it at creation of MaterialSegmentedControl with `segments:` parameter, then it is not working.

**Comment by twho** [comment]
Right, I did notice that. The crash was because the segments and selector are `nil`. I will roll out an update to address this.
